// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGRoloSO6jWJAnC0WrXWllxv_pBzkdt4',
    appId: '1:411539668234:web:d7a047e54cc169e90b8ef3',
    messagingSenderId: '411539668234',
    projectId: 'expense-tracker-9dd35',
    authDomain: 'expense-tracker-9dd35.firebaseapp.com',
    storageBucket: 'expense-tracker-9dd35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHKbiJYQ4KykvCADPsM2dgV2WfHzUXs4',
    appId: '1:411539668234:android:09187ef96a9445c80b8ef3',
    messagingSenderId: '411539668234',
    projectId: 'expense-tracker-9dd35',
    storageBucket: 'expense-tracker-9dd35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tiicNRsqCJg3_7Nu3oTqrWkIMzwjoAg',
    appId: '1:411539668234:ios:ae790b2194034be10b8ef3',
    messagingSenderId: '411539668234',
    projectId: 'expense-tracker-9dd35',
    storageBucket: 'expense-tracker-9dd35.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tiicNRsqCJg3_7Nu3oTqrWkIMzwjoAg',
    appId: '1:411539668234:ios:ae790b2194034be10b8ef3',
    messagingSenderId: '411539668234',
    projectId: 'expense-tracker-9dd35',
    storageBucket: 'expense-tracker-9dd35.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpGRoloSO6jWJAnC0WrXWllxv_pBzkdt4',
    appId: '1:411539668234:web:412b865039e8323f0b8ef3',
    messagingSenderId: '411539668234',
    projectId: 'expense-tracker-9dd35',
    authDomain: 'expense-tracker-9dd35.firebaseapp.com',
    storageBucket: 'expense-tracker-9dd35.firebasestorage.app',
  );
}
